### ISSUE TITLE
Enter the frontend in the list of games Lubuntu (or other distro) with an icon

### ISSUE THREAD

**Issue by Caligo77** [nicolas-van/lightningmf#7]
I need an icon for your frontend and can see the shortcut in the games section of Lubuntu. Now you can just create a custom shortcut on the desktop, but it is not easy to include an icon in the panel of LXDE Lubuntu, requires action by hand in the code of LXDE to add an icon to the interface. After installing the icon to appear in the games section of Lubuntu could easily include it in the main panel.

**Comment by nicolas-van** [comment]
I won't do it.

Creating icons is system-dependent, even configuration-dependent in the case of Linux which can have a lot of different desktop environments. Creating an icon is not the same on LXDE, on Gnome, on KDE, on Windows, on Mac OSX, etc...

For lightningmf I chose to not provide multiple installation packages. Previously I tried to provide one package for Ubuntu and it was a hell of a thing to maintain. So I gave up. Now I only provide a pypi package that should work on all systems and that's all.

So, yeah, you should create your own icon on whatever desktop you are using. Because if it's difficult for you it will 100 times more for me to provide icons for all desktops.
